# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    twig:
        mode: lazy
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # controller:
    #     filter_action:          liip_imagine.controller:filterAction
    #     filter_runtime_action:  liip_imagine.controller:filterRuntimeAction
    #     redirect_response_code: 301

    filter_sets:
        mini:
            quality: 75
            filters:
                thumbnail:
                    size: [150, 100]
                    mode: outbound

        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound

        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 530]
                    mode: outbound