controllers:
    resource: ../../src/Controller/
    type: annotation

admin_constrollers:
    name_prefix: admin_
    prefix: '%admin_route_prefix%'
    resource: ../../src/Admin/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
